### PR TITLE
Pull Request for adding blog post for linking custom domain name

### PR DESCRIPTION
**Pull request by Evan-Callaghan**

### CODE REVIEW

**Comment by JacobH93** [comment]
Hey Evan, I think everything looks really good. The only suggestion I have is adding some line breaks <br> between the items on your first ordered list and right after the end of your unordered list. It's not a big deal at all obviously but I think it might enhance the readability a little bit.

**Review by ogennadi — CHANGES_REQUESTED** [review]
1. Please add a link in index.html to your new file
2. Please add your partner's time logs to the end of this file as well

**Comment by morgangant16** [comment]
I think it looks very good!!

**Review by Evan-Callaghan — COMMENTED** [review]
Adjustments based on feedback

**Pull request merged**
